-- Rol dedicado del proyecto + grants sobre las 3 DBs medallion (Bronze / Silver / Gold)
-- Rol del proyecto: separa permisos del ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS ROLE_NYCBIKE
    COMMENT = 'Rol opera sobre DEV_/PRO_CITYBIKE_BRONZE, DEV_/PRO_CITYBIKE_SILVER/GOLD y WH_NYCBIKE_DEV/PRO';

-- Permisos sobre los warehouses (DEV y PRO separados para atribucion de costes)
GRANT USAGE, OPERATE ON WAREHOUSE WH_NYCBIKE_DEV TO ROLE ROLE_NYCBIKE;
GRANT USAGE, OPERATE ON WAREHOUSE WH_NYCBIKE_PRO TO ROLE ROLE_NYCBIKE;
GRANT USAGE, OPERATE ON WAREHOUSE WH_ANALISIS    TO ROLE ROLE_NYCBIKE;

-- Permiso necesario para crear / ejecutar TASKS (automatizacion Bronze)
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROLE_NYCBIKE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE ROLE_NYCBIKE;

-- Permisos sobre las databases medallion (DEV_ para __Snowflake, PRO_ para dbt)
GRANT USAGE ON DATABASE DEV_CITYBIKE_BRONZE TO ROLE ROLE_NYCBIKE;
GRANT USAGE ON DATABASE PRO_CITYBIKE_BRONZE TO ROLE ROLE_NYCBIKE;
GRANT USAGE ON DATABASE DEV_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT USAGE ON DATABASE PRO_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT USAGE ON DATABASE DEV_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;
GRANT USAGE ON DATABASE PRO_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;
GRANT USAGE ON DATABASE DB_CITYBIKE_LOGS TO ROLE ROLE_NYCBIKE;

-- Permiso para crear schemas en Silver y Gold (DEV_ y PRO_)
GRANT CREATE SCHEMA ON DATABASE DEV_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT CREATE SCHEMA ON DATABASE PRO_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT CREATE SCHEMA ON DATABASE DEV_CITYBIKE_GOLD TO ROLE ROLE_NYCBIKE;
GRANT CREATE SCHEMA ON DATABASE PRO_CITYBIKE_GOLD TO ROLE ROLE_NYCBIKE;
GRANT CREATE SCHEMA ON DATABASE DB_CITYBIKE_LOGS TO ROLE ROLE_NYCBIKE;


-- Permisos sobre el schema CITYBIKE Bronze (tablas, stages, file formats, procedures)
GRANT USAGE, CREATE TABLE, CREATE PIPE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA DEV_CITYBIKE_BRONZE.CITYBIKE TO ROLE ROLE_NYCBIKE;

-- Permisos sobre el schema PRO CITYBIKE Bronze (tablas, stages, file formats, procedures)
GRANT USAGE, CREATE TABLE, CREATE PIPE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA PRO_CITYBIKE_BRONZE.CITYBIKE TO ROLE ROLE_NYCBIKE;

-- Permisos sobre el schema NOAA BRONZE (ingesta cruda: tablas, stages, streams, tasks, procedures)
GRANT USAGE, CREATE TABLE, CREATE PIPE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA DEV_CITYBIKE_BRONZE.NOAA TO ROLE ROLE_NYCBIKE;

-- Permisos sobre el schema PRO NOAA BRONZE (ingesta cruda: tablas, stages, streams, tasks, procedures)
GRANT USAGE, CREATE TABLE, CREATE PIPE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA PRO_CITYBIKE_BRONZE.NOAA TO ROLE ROLE_NYCBIKE;
    
-- Permisos sobre el schema CITYBIKE Bronze (tablas, stages, file formats, procedures)
GRANT USAGE, CREATE TABLE, CREATE PIPE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA DB_CITYBIKE_LOGS.LOGS TO ROLE ROLE_NYCBIKE;

-- Permisos sobre el schema CITYBIKE Bronze (tablas, stages, file formats, procedures)
GRANT USAGE, CREATE TABLE, CREATE PIPE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA DB_CITYBIKE_LOGS.PRO TO ROLE ROLE_NYCBIKE;

-- Acceso a futuros objetos (tablas) en cada schema
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_CITYBIKE_BRONZE.CITYBIKE TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_CITYBIKE_BRONZE.NOAA TO ROLE ROLE_NYCBIKE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA PRO_CITYBIKE_BRONZE.CITYBIKE TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA PRO_CITYBIKE_BRONZE.NOAA TO ROLE ROLE_NYCBIKE;

-- Acceso a futuros objetos (vistas) en cada schema
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEV_CITYBIKE_BRONZE.CITYBIKE TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEV_CITYBIKE_BRONZE.NOAA TO ROLE ROLE_NYCBIKE;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA PRO_CITYBIKE_BRONZE.CITYBIKE TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PRO_CITYBIKE_BRONZE.NOAA TO ROLE ROLE_NYCBIKE;

-- Para soportar schemas custom que dbt pueda crear dinamicamente en Silver y Gold (DEV_ y PRO_)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE DEV_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE PRO_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE DEV_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE PRO_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DB_CITYBIKE_LOGS TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DEV_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE PRO_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DEV_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE PRO_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;

-- Asignar el rol al usuario actual
SET current_user_name = CURRENT_USER();
GRANT ROLE ROLE_NYCBIKE TO USER IDENTIFIER($current_user_name);
