-- -----------------------------------------------------------------------------
-- 3. Rol dedicado para el proyecto + grants
--    Idea: separar permisos del proyecto del ACCOUNTADMIN. Despues de este
--    script, todo el trabajo de ingesta se hace con ROLE_NYCBIKE.
-- -----------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS ROLE_NYCBIKE
    COMMENT = 'Rol del proyecto NYCBIKE: opera sobre NYCBIKE_DWH y WH_NYCBIKE_DEV';

-- Permisos sobre el warehouse
GRANT USAGE, OPERATE ON WAREHOUSE WH_NYCBIKE_DEV TO ROLE ROLE_NYCBIKE;

-- Permiso necesario para crear / ejecutar TASKS (automatizacion Bronze)
-- Solo ACCOUNTADMIN puede otorgarlo.
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROLE_NYCBIKE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE ROLE_NYCBIKE;

-- Permisos sobre la base de datos y esquemas
GRANT USAGE ON DATABASE WH_NYCBIKE TO ROLE ROLE_NYCBIKE;
GRANT USAGE, CREATE TABLE,CREATE PIPE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA WH_NYCBIKE.bronze TO ROLE ROLE_NYCBIKE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA WH_NYCBIKE.silver TO ROLE ROLE_NYCBIKE;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA WH_NYCBIKE.gold TO ROLE ROLE_NYCBIKE;


-- Acceso a futuros objetos creados dentro de cada esquema
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA WH_NYCBIKE.bronze TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA WH_NYCBIKE.silver TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA WH_NYCBIKE.gold   TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA WH_NYCBIKE.bronze TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA WH_NYCBIKE.silver TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA WH_NYCBIKE.gold   TO ROLE ROLE_NYCBIKE;


SET current_user_name = CURRENT_USER();
GRANT ROLE ROLE_NYCBIKE TO USER IDENTIFIER($current_user_name);