-- Rol dedicado del proyecto + grants sobre las 3 DBs medallion (Bronze / Silver / Gold)

-- Rol del proyecto: separa permisos del ACCOUNTADMIN
CREATE ROLE IF NOT EXISTS ROLE_NYCBIKE
    COMMENT = 'Rol del proyecto NYCBIKE: opera sobre DB_CITYBIKE_BRONZE/SILVER/GOLD y WH_NYCBIKE_DEV';

-- Permisos sobre el warehouse
GRANT USAGE, OPERATE ON WAREHOUSE WH_NYCBIKE_DEV TO ROLE ROLE_NYCBIKE;

-- Permiso necesario para crear / ejecutar TASKS (automatizacion Bronze)
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROLE_NYCBIKE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE ROLE_NYCBIKE;

-- Permisos sobre las 3 databases medallion
GRANT USAGE ON DATABASE DB_CITYBIKE_BRONZE TO ROLE ROLE_NYCBIKE;
GRANT USAGE ON DATABASE DB_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT USAGE ON DATABASE DB_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;

-- Permiso para crear schemas en Silver y Gold (dbt suele crear schemas custom como SILVER_<dev>)
GRANT CREATE SCHEMA ON DATABASE DB_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT CREATE SCHEMA ON DATABASE DB_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;

-- Permisos sobre el schema BRONZE (ingesta cruda: tablas, stages, streams, tasks, procedures)
GRANT USAGE, CREATE TABLE, CREATE PIPE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA DB_CITYBIKE_BRONZE.BRONZE TO ROLE ROLE_NYCBIKE;

-- Permisos sobre el schema SILVER (modelos dbt limpios)
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA DB_CITYBIKE_SILVER.SILVER TO ROLE ROLE_NYCBIKE;

-- Permisos sobre el schema GOLD (datamarts dbt)
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION
    ON SCHEMA DB_CITYBIKE_GOLD.GOLD TO ROLE ROLE_NYCBIKE;

-- Acceso a futuros objetos (tablas) en cada schema
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA DB_CITYBIKE_BRONZE.BRONZE TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA DB_CITYBIKE_SILVER.SILVER TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA DB_CITYBIKE_GOLD.GOLD     TO ROLE ROLE_NYCBIKE;

-- Acceso a futuros objetos (vistas) en cada schema
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DB_CITYBIKE_BRONZE.BRONZE TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DB_CITYBIKE_SILVER.SILVER TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DB_CITYBIKE_GOLD.GOLD     TO ROLE ROLE_NYCBIKE;

-- Para soportar schemas custom que dbt pueda crear dinamicamente en Silver y Gold
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE DB_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE DB_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DB_CITYBIKE_SILVER TO ROLE ROLE_NYCBIKE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DB_CITYBIKE_GOLD   TO ROLE ROLE_NYCBIKE;

-- Asignar el rol al usuario actual
SET current_user_name = CURRENT_USER();
GRANT ROLE ROLE_NYCBIKE TO USER IDENTIFIER($current_user_name);
