-- Conecta Snowflake con el repo de GitHub Rlizaran/Snowflake_proyect (DEV_CITYBIKE_BRONZE)

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_NYCBIKE_DEV;
USE DATABASE DEV_CITYBIKE_BRONZE;
USE SCHEMA   CITYBIKE;

-- API_INTEGRATION hacia GitHub (solo referencia el SECRET, no el token)
CREATE OR REPLACE API INTEGRATION github_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES  = ('https://github.com/Rlizaran/')
  ALLOWED_AUTHENTICATION_SECRETS = (DEV_CITYBIKE_BRONZE.CITYBIKE.GITHUB_PAT)
  ENABLED = TRUE;

-- GIT REPOSITORY apuntando al repo de GitHub
CREATE OR REPLACE GIT REPOSITORY DEV_CITYBIKE_BRONZE.CITYBIKE.CITIBIKE_REPO
  API_INTEGRATION = github_api_integration
  GIT_CREDENTIALS = DEV_CITYBIKE_BRONZE.CITYBIKE.GITHUB_PAT
  ORIGIN = 'https://github.com/Rlizaran/Snowflake_proyect.git';

-- Verificaciones
SHOW GIT BRANCHES IN DEV_CITYBIKE_BRONZE.CITYBIKE.CITIBIKE_REPO;
LS @DEV_CITYBIKE_BRONZE.CITYBIKE.CITIBIKE_REPO/branches/main/;
