-- CLONING de DEV_BRONZE_DB.CITYBIKE a PRO
CREATE OR REPLACE TABLE PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_TRIPS_JC CLONE DEV_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_TRIPS_JC;
CREATE OR REPLACE TABLE PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_TRIPS_NY CLONE DEV_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_TRIPS_NY;

-- CLONING de DEV_BRONZE_DB.NOAA a PRO
CREATE OR REPLACE TABLE PRO_CITYBIKE_BRONZE.NOAA.NOAA_RAW_YEAR CLONE DEV_CITYBIKE_BRONZE.NOAA.NOAA_RAW_YEAR;