-- Streams + Tasks Bronze DEV: NY S3, NY interno (202604+), JC interno, NOAA.
-- Root unico TSK_BRONZE_MASTER con CRON dia 28 a las 03:00 NY; las 3 chains corren AFTER MASTER.

USE ROLE ROLE_NYCBIKE;
USE WAREHOUSE WH_NYCBIKE_DEV;
USE DATABASE DB_CITYBIKE_LOGS;
USE SCHEMA LOGS;

-- Stream append-only sobre CityBike NYC
CREATE OR REPLACE STREAM STM_CITYBIKE_NY
    ON TABLE DEV_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_TRIPS_NY APPEND_ONLY = TRUE;

-- Stream append-only sobre CityBike Jersey City
CREATE OR REPLACE STREAM STM_CITYBIKE_JC
    ON TABLE DEV_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_TRIPS_JC APPEND_ONLY = TRUE;

-- Stream sobre el stage interno de Jersey City (detecta archivos nuevos)
CREATE OR REPLACE STREAM STM_CITYBIKE_JC_STAGE
    ON STAGE DEV_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_LANDING_STAGE;

-- Stream sobre el stage interno de Manhattan (202604+, Citi Bike cambio formato)
CREATE OR REPLACE STREAM STM_CITYBIKE_NY_STAGE
    ON STAGE DEV_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_LANDING_STAGE_NY;

-- Stream append-only sobre NOAA (consumo incremental por Silver)
CREATE OR REPLACE STREAM STM_NOAA_YEAR
    ON TABLE DEV_CITYBIKE_BRONZE.NOAA.NOAA_RAW_YEAR APPEND_ONLY = TRUE;

/*
                MASTER: unica root con CRON. Las 3 chains arrancan AFTER MASTER.
*/
CREATE OR REPLACE TASK TSK_BRONZE_MASTER
    WAREHOUSE = WH_NYCBIKE_DEV
    SCHEDULE  = 'USING CRON 0 3 28 * * America/New_York'
AS SELECT CURRENT_TIMESTAMP();

/*
                CHAIN 1 (NY S3 publico): meses 2024-01 .. 2026-03
*/
CREATE OR REPLACE TASK TSK_BRONZE_CITYBIKE_NY
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_MASTER
AS CALL DEV_CITYBIKE_BRONZE.CITYBIKE.LOAD_CITYBIKE_NY();

/*
                CHAIN 2 (NY stage interno): meses 2026-04+ via Python PUT
*/
CREATE OR REPLACE TASK TSK_BRONZE_NY_INT_REFRESH
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_MASTER
AS CALL DEV_CITYBIKE_BRONZE.CITYBIKE.REFRESH_NY_STAGE();

CREATE OR REPLACE TASK TSK_BRONZE_NY_INT_ONFILES
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_NY_INT_REFRESH
    WHEN SYSTEM$STREAM_HAS_DATA('DB_CITYBIKE_LOGS.LOGS.STM_CITYBIKE_NY_STAGE')
AS CALL DEV_CITYBIKE_BRONZE.CITYBIKE.LOAD_CITYBIKE_NY_INT();

-- Procedure: drena el stream del stage NY para que el WHEN del proximo refresh evalue limpio
CREATE OR REPLACE PROCEDURE DRAIN_NY_STAGE_STREAM()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    INSERT INTO LOAD_LOG (task_name, outcome, details)
    SELECT 'STM_CITYBIKE_NY_STAGE', 'DRAIN', 'archivos_consumidos=' || COUNT(*)
    FROM STM_CITYBIKE_NY_STAGE;

    RETURN 'Stage stream NY drenado';

EXCEPTION
    WHEN OTHER THEN
        INSERT INTO LOAD_LOG (task_name, outcome, details)
        VALUES ('DRAIN_NY_STAGE_STREAM', 'ERROR', :SQLERRM);
        RAISE;
END;

CREATE OR REPLACE TASK TSK_BRONZE_NY_INT_DRAIN
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_NY_INT_ONFILES
AS CALL DRAIN_NY_STAGE_STREAM();

/*
                CHAIN 3 (JC stage interno): upload manual via Python PUT
*/
CREATE OR REPLACE TASK TSK_BRONZE_JC_REFRESH
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_MASTER
AS CALL DEV_CITYBIKE_BRONZE.CITYBIKE.REFRESH_JC_STAGE();

CREATE OR REPLACE TASK TSK_BRONZE_JC_ONFILES
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_JC_REFRESH
    WHEN SYSTEM$STREAM_HAS_DATA('DB_CITYBIKE_LOGS.LOGS.STM_CITYBIKE_JC_STAGE')
AS CALL DEV_CITYBIKE_BRONZE.CITYBIKE.LOAD_CITYBIKE_JC();

-- Procedure: drena el stream del stage JC para que el WHEN del proximo refresh evalue limpio
CREATE OR REPLACE PROCEDURE DRAIN_JC_STAGE_STREAM()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    INSERT INTO LOAD_LOG (task_name, outcome, details)
    SELECT 'STM_CITYBIKE_JC_STAGE', 'DRAIN', 'archivos_consumidos=' || COUNT(*)
    FROM STM_CITYBIKE_JC_STAGE;

    RETURN 'Stage stream JC drenado';

EXCEPTION
    WHEN OTHER THEN
        INSERT INTO LOAD_LOG (task_name, outcome, details)
        VALUES ('DRAIN_JC_STAGE_STREAM', 'ERROR', :SQLERRM);
        RAISE;
END;

CREATE OR REPLACE TASK TSK_BRONZE_JC_DRAIN
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_JC_ONFILES
AS CALL DRAIN_JC_STAGE_STREAM();

/*
                NOAA: AFTER las 3 chains de citybike. WHEN streams citybike tienen datos.
*/
CREATE OR REPLACE TASK TSK_BRONZE_NOAA
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_CITYBIKE_NY, TSK_BRONZE_NY_INT_DRAIN, TSK_BRONZE_JC_DRAIN
    WHEN SYSTEM$STREAM_HAS_DATA('DB_CITYBIKE_LOGS.LOGS.STM_CITYBIKE_NY')
      OR SYSTEM$STREAM_HAS_DATA('DB_CITYBIKE_LOGS.LOGS.STM_CITYBIKE_JC')
AS CALL DEV_CITYBIKE_BRONZE.NOAA.LOAD_NOAA_YEAR();

-- Procedure: drena los table streams STM_CITYBIKE_NY y STM_CITYBIKE_JC.
-- Sin esto, los streams quedan en estado "con datos" para siempre y el WHEN de TSK_BRONZE_NOAA
-- siempre evalua TRUE despues del primer run.
CREATE OR REPLACE PROCEDURE DRAIN_CITYBIKE_TABLE_STREAMS()
RETURNS STRING
LANGUAGE SQL
AS
DECLARE
    v_ny NUMBER := 0;
    v_jc NUMBER := 0;
BEGIN
    -- Insert + SELECT FROM stream avanza el offset del stream
    INSERT INTO LOAD_LOG (task_name, outcome, details)
    SELECT 'STM_CITYBIKE_NY', 'DRAIN', 'rows_consumidas=' || COUNT(*)
    FROM STM_CITYBIKE_NY;

    INSERT INTO LOAD_LOG (task_name, outcome, details)
    SELECT 'STM_CITYBIKE_JC', 'DRAIN', 'rows_consumidas=' || COUNT(*)
    FROM STM_CITYBIKE_JC;

    RETURN 'Table streams citybike drenados';

EXCEPTION
    WHEN OTHER THEN
        INSERT INTO LOAD_LOG (task_name, outcome, details)
        VALUES ('DRAIN_CITYBIKE_TABLE_STREAMS', 'ERROR', :SQLERRM);
        RAISE;
END;

-- Task de cierre: drena los table streams DESPUES de NOAA para que el WHEN del proximo cycle
-- empiece "sin datos" y solo evalue TRUE cuando citybike vuelva a insertar.
CREATE OR REPLACE TASK TSK_BRONZE_CITYBIKE_STREAMS_DRAIN
    WAREHOUSE = WH_NYCBIKE_DEV
    AFTER TSK_BRONZE_NOAA
AS CALL DRAIN_CITYBIKE_TABLE_STREAMS();
