-- Control de tasks Bronze: RESUME / SUSPEND / EXECUTE + verificaciones (CITYBIKE / NOAA)

-- Conectar usuario, warehouse y database
USE ROLE ROLE_NYCBIKE;
USE WAREHOUSE WH_NYCBIKE_DEV;
USE DATABASE DB_CITYBIKE_LOGS;

-- Activar primero los hijos del DAG, despues los padres (regla Snowflake)
ALTER TASK LOGS.TSK_BRONZE_JC_DRAIN RESUME;
ALTER TASK LOGS.TSK_BRONZE_JC_ONFILES RESUME;
ALTER TASK LOGS.TSK_BRONZE_JC_REFRESH RESUME;
ALTER TASK LOGS.TSK_BRONZE_NOAA RESUME;
ALTER TASK LOGS.TSK_BRONZE_CITYBIKE RESUME;


-- Suspender todo para ahorrar creditos (descomentar)
-- ALTER TASK LOGS.TSK_BRONZE_CITYBIKE SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_NOAA SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_JC_REFRESH SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_JC_ONFILES SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_JC_DRAIN SUSPEND;

-- Ejecucion manual sin esperar el cron (forzar para demo)
-- EXECUTE TASK DB_CITYBIKE_LOGS.LOGS.TSK_BRONZE_CITYBIKE;
-- EXECUTE TASK DB_CITYBIKE_LOGS.LOGS.TSK_BRONZE_JC_REFRESH;

-- Verificacion de tasks por schema
SHOW TASKS IN SCHEMA DB_CITYBIKE_LOGS.LOGS;

-- Verificacion de streams por schema
SHOW STREAMS IN SCHEMA DB_CITYBIKE_LOGS.LOGS;

-- Verificacion historial de ejecuciones de tasks (ultimos 7 dias)
SELECT *
FROM TABLE(DB_CITYBIKE_LOGS.INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME ILIKE '%TSK%'
ORDER BY scheduled_time DESC
LIMIT 30;

-- Ultimos 20 eventos del log propio (procedures, drains, demos)
SELECT *
FROM LOGS.LOAD_LOG
ORDER BY run_ts DESC 
LIMIT 20;