-- Control de tasks Bronze: RESUME / SUSPEND / EXECUTE + verificaciones (CITYBIKE / NOAA)

-- Conectar usuario, warehouse y database
USE ROLE ROLE_NYCBIKE;
USE WAREHOUSE WH_NYCBIKE_DEV;
USE DATABASE DB_CITYBIKE_LOGS;

-- 1. Tarea Final (La que depende de todos los DRAINs)
ALTER TASK LOGS.TSK_BRONZE_NOAA RESUME;

-- 2. Capa de DRAIN (Dependen de ONFILES)
ALTER TASK LOGS.TSK_BRONZE_JC_DRAIN RESUME;
ALTER TASK LOGS.TSK_BRONZE_NY_INT_DRAIN RESUME;

-- 3. Capa de ONFILES (Dependen de REFRESH)
ALTER TASK LOGS.TSK_BRONZE_JC_ONFILES RESUME;
ALTER TASK LOGS.TSK_BRONZE_NY_INT_ONFILES RESUME;

-- 4. Capa Raíz (Las que tienen el SCHEDULE / CRON)
ALTER TASK LOGS.TSK_BRONZE_CITYBIKE_NY RESUME;
ALTER TASK LOGS.TSK_BRONZE_JC_REFRESH RESUME;
ALTER TASK LOGS.TSK_BRONZE_NY_INT_REFRESH RESUME;
ALTER TASK LOGS.TSK_BRONZE_MASTER RESUME;



-- Suspender todo para ahorrar creditos (descomentar)
-- ALTER TASK LOGS.TSK_BRONZE_MASTER SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_NOAA SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_JC_DRAIN SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_NY_INT_DRAIN SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_JC_ONFILES SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_NY_INT_ONFILES SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_CITYBIKE_NY SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_JC_REFRESH SUSPEND;
-- ALTER TASK LOGS.TSK_BRONZE_NY_INT_REFRESH SUSPEND;


-- Ejecucion manual sin esperar el cron (forzar para demo)
-- EXECUTE TASK DB_CITYBIKE_LOGS.LOGS.TSK_BRONZE_MASTER;

-- Verificacion de tasks por schema
SHOW TASKS IN SCHEMA DB_CITYBIKE_LOGS.LOGS;

-- Verificacion de streams por schema
SHOW STREAMS IN SCHEMA DB_CITYBIKE_LOGS.LOGS;

-- Verificacion historial de ejecuciones de tasks (ultimos 7 dias)
SELECT *
FROM TABLE(DB_CITYBIKE_LOGS.INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME ILIKE '%TSK%'
ORDER BY scheduled_time DESC
LIMIT 30;

-- Ultimos 20 eventos del log propio (procedures, drains, demos)
SELECT *
FROM LOGS.LOAD_LOG
ORDER BY run_ts DESC;