-- Control de tasks Bronze: RESUME / SUSPEND / EXECUTE + verificaciones (DB_CITYBIKE_BRONZE)

-- Conectar usuario, warehouse y database
USE ROLE ROLE_NYCBIKE;
USE WAREHOUSE WH_NYCBIKE_DEV;
USE DATABASE DB_CITYBIKE_BRONZE;
USE SCHEMA   BRONZE;

-- Activar hijos primero, despues padres
ALTER TASK BRONZE.TSK_BRONZE_NOAA RESUME;
ALTER TASK BRONZE.TSK_BRONZE_CITYBIKE RESUME;
ALTER TASK BRONZE.TSK_BRONZE_JC_DRAIN RESUME;
ALTER TASK BRONZE.TSK_BRONZE_JC_ONFILES RESUME;
ALTER TASK BRONZE.TSK_BRONZE_JC_REFRESH RESUME;

-- Suspender todo para ahorrar creditos (descomentar)
-- ALTER TASK BRONZE.TSK_BRONZE_CITYBIKE SUSPEND;
-- ALTER TASK BRONZE.TSK_BRONZE_NOAA SUSPEND;
-- ALTER TASK BRONZE.TSK_BRONZE_JC_REFRESH SUSPEND;
-- ALTER TASK BRONZE.TSK_BRONZE_JC_ONFILES SUSPEND;

-- Ejecutar el task padre manualmente sin esperar el cron
-- EXECUTE TASK BRONZE.TSK_BRONZE_CITYBIKE;
-- EXECUTE TASK BRONZE.TSK_BRONZE_NOAA;
-- EXECUTE TASK BRONZE.TSK_BRONZE_JC_REFRESH;

-- Verificacion de tasks y streams actuales
SHOW TASKS IN SCHEMA DB_CITYBIKE_BRONZE.BRONZE;
SHOW STREAMS IN SCHEMA DB_CITYBIKE_BRONZE.BRONZE;

-- Verificacion historial de ejecuciones de tasks (ultimos 7 dias)
SELECT  *
FROM    TABLE(DB_CITYBIKE_BRONZE.INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME ILIKE '%tsk%'
ORDER BY scheduled_time DESC
LIMIT 20;

-- Verificacion: ultimos 20 eventos del log propio
SELECT * FROM BRONZE.LOAD_LOG ORDER BY run_ts DESC LIMIT 20;
