-- Creacion de FILE FORMATS y STAGES en DEV_CITYBIKE_BRONZE.BRONZE para cargar los datos crudos

USE ROLE ROLE_NYCBIKE;
USE WAREHOUSE WH_NYCBIKE_DEV;
USE DATABASE PRO_CITYBIKE_BRONZE;
USE SCHEMA   CITYBIKE;

-- File Format CSV para CityBike NY (header de 3 lineas, evita error UTF8)
CREATE OR REPLACE FILE FORMAT PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_NY_CSV
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 3
  REPLACE_INVALID_CHARACTERS = TRUE
  NULL_IF = ('NULL', '\\N', '')
  COMPRESSION = AUTO;

-- File Format CSV para CityBike Jersey City (header simple)
CREATE OR REPLACE FILE FORMAT PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_JC_CSV
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  REPLACE_INVALID_CHARACTERS = TRUE
  NULL_IF = ('NULL', '\\N', '')
  COMPRESSION = AUTO;

-- File Format CSV para NOAA (sin header)
CREATE OR REPLACE FILE FORMAT PRO_CITYBIKE_BRONZE.NOAA.NOAA_CSV
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 0
  REPLACE_INVALID_CHARACTERS = TRUE
  NULL_IF = ('NULL', '\\N', '')
  COMPRESSION = AUTO;

-- Stage externo apuntando al bucket publico de CityBike NYC
CREATE OR REPLACE STAGE PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_S3_STAGE
    URL = 's3://tripdata'
    FILE_FORMAT = PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_NY_CSV
    COMMENT = 'Bucket publico de CityBike NYC';

-- Stage interno (landing) para JC: el script Python sube aqui los CSV mensuales
CREATE OR REPLACE STAGE PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_LANDING_STAGE
    FILE_FORMAT = PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_JC_CSV
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Landing stage interno para Jersey City (Python PUT)';

-- Stage interno (landing) para NY: el script Python sube aqui los CSV mensuales
CREATE OR REPLACE STAGE PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_LANDING_STAGE_NY
    FILE_FORMAT = PRO_CITYBIKE_BRONZE.CITYBIKE.CITYBIKE_JC_CSV
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Landing stage interno para Manhattan (Python PUT)';

-- Stage externo apuntando al bucket publico NOAA by station
CREATE OR REPLACE STAGE PRO_CITYBIKE_BRONZE.NOAA.NOAA_S3_STAGE_STATION
    URL = 's3://noaa-ghcn-pds/csv.gz/by_station/'
    FILE_FORMAT = PRO_CITYBIKE_BRONZE.NOAA.NOAA_CSV
    COMMENT = 'Bucket publico NOAA by station';

-- Stage externo apuntando al bucket publico NOAA by year
CREATE OR REPLACE STAGE PRO_CITYBIKE_BRONZE.NOAA.NOAA_S3_STAGE_YEAR
    URL = 's3://noaa-ghcn-pds/csv.gz/by_year/'
    FILE_FORMAT = PRO_CITYBIKE_BRONZE.NOAA.NOAA_CSV
    COMMENT = 'Bucket publico NOAA by year';
