-- Control de tasks Bronze: RESUME / SUSPEND / EXECUTE + verificaciones (CITYBIKE / NOAA)

-- Conectar usuario, warehouse y database
USE ROLE ROLE_NYCBIKE;
USE WAREHOUSE WH_NYCBIKE_PRO;
USE DATABASE DB_CITYBIKE_LOGS;
USE SCHEMA PRO;

-- 1. Cierre del cycle (drena table streams tras NOAA)
ALTER TASK PRO.TSK_BRONZE_CITYBIKE_STREAMS_DRAIN RESUME;

-- 2. Tarea Final (La que depende de todos los DRAINs)
ALTER TASK PRO.TSK_BRONZE_NOAA RESUME;

-- 3. Capa de DRAIN (Dependen de ONFILES)
ALTER TASK PRO.TSK_BRONZE_JC_DRAIN RESUME;
ALTER TASK PRO.TSK_BRONZE_NY_INT_DRAIN RESUME;

-- 4. Capa de ONFILES (Dependen de REFRESH)
ALTER TASK PRO.TSK_BRONZE_JC_ONFILES RESUME;
ALTER TASK PRO.TSK_BRONZE_NY_INT_ONFILES RESUME;

-- 5. Capa intermedia (AFTER MASTER)
ALTER TASK PRO.TSK_BRONZE_CITYBIKE_NY RESUME;
ALTER TASK PRO.TSK_BRONZE_JC_REFRESH RESUME;
ALTER TASK PRO.TSK_BRONZE_NY_INT_REFRESH RESUME;

-- 6. Root con CRON (siempre se resume el ultimo)
ALTER TASK PRO.TSK_BRONZE_MASTER RESUME;


-- Suspender todo para ahorrar creditos (descomentar)
-- ALTER TASK PRO.TSK_BRONZE_MASTER SUSPEND;
-- ALTER TASK PRO.TSK_BRONZE_NOAA SUSPEND;
-- ALTER TASK PRO.TSK_BRONZE_JC_DRAIN SUSPEND;
-- ALTER TASK PRO.TSK_BRONZE_NY_INT_DRAIN SUSPEND;
-- ALTER TASK PRO.TSK_BRONZE_JC_ONFILES SUSPEND;
-- ALTER TASK PRO.TSK_BRONZE_NY_INT_ONFILES SUSPEND;
-- ALTER TASK PRO.TSK_BRONZE_CITYBIKE_NY SUSPEND;
-- ALTER TASK PRO.TSK_BRONZE_JC_REFRESH SUSPEND;
-- ALTER TASK PRO.TSK_BRONZE_NY_INT_REFRESH SUSPEND;


-- Ejecucion manual sin esperar el cron (forzar para demo)
-- EXECUTE TASK DB_CITYBIKE_LOGS.PRO.TSK_BRONZE_MASTER;

-- Verificacion de tasks por schema
SHOW TASKS IN SCHEMA DB_CITYBIKE_LOGS.PRO;

-- Verificacion de streams por schema
SHOW STREAMS IN SCHEMA DB_CITYBIKE_LOGS.PRO;

-- Verificacion historial de ejecuciones de tasks (ultimos 7 dias)
SELECT *
FROM TABLE(DB_CITYBIKE_LOGS.INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME ILIKE '%TSK%' and SCHEMA_NAME ilike 'pro'
ORDER BY scheduled_time DESC
LIMIT 30;


-- Ultimos 20 eventos del log propio (procedures, drains, demos)
SELECT *
FROM PRO.LOAD_LOG
ORDER BY run_ts DESC 
LIMIT 20;